name: Dockerk Build for Master
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: cloudnativegbb/arcdemo-data-api@master
      with:
        name: docker.pkg.github.com/cloudnativegbb/arc-k8s-demos/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
